### Intoducation and  Creation of DataFrames

**1. What is DataFrame?**

A DataFrame is a two-dimensional, labeled data structure that stores data in rows and columns, allowing each column to hold values of different data types.

A data structure is a way of organizing, storing, and managing data in a computer so that it can be used efficiently.

It is designed for handling and analyzing structured (tabular) data efficiently.

A DataFrame is:

* Two-dimensional: Data is arranged in rows and columns.
* Labeled: Each row has an index (like row numbers), and each column has a name.
* Flexible: Can store different data types in different columns (numbers, text, dates, etc.).
* Mutable: You can change, add, or delete rows and columns anytime.

### Example

| Name  | Age | City   |
| ----- | --: | ------ |
| Aman  |  25 | Delhi  |
| Ankit |  30 | Patna  |
| Ayush |  35 | Kanpur |

This is a DataFrame with:

* 3 rows
* 3 columns (`Name`, `Age`, `City`)

**2. Different ways to create DataFrame?**

In [1]:
# import numpy and pandas
import pandas as pd
import numpy as np

1. From a Dictionary of Lists

In [2]:
data = {
    "Name" : ["Amit", "Anand", "Akash"],
    "Age"  : [25, 28 , 30],
    "CIty" : ["Mumbai", 'Delhi', "Patna"]
}
data

{'Name': ['Amit', 'Anand', 'Akash'],
 'Age': [25, 28, 30],
 'CIty': ['Mumbai', 'Delhi', 'Patna']}

In [3]:
df =pd.DataFrame(data)
df.head()

    Name  Age    CIty
0   Amit   25  Mumbai
1  Anand   28   Delhi
2  Akash   30   Patna

```text
pd.DataFrame() args

pandas.DataFrame(
    data=None, # The actual content of the DataFrame.
    index=None, # Row labels (default is 0,1,2,...). Can be list-like
    columns=None, # Column labels (default is inferred from data)
    dtype=None, # Data type to force all columns to be
    copy=False # (Default- False)If True, it copies the data. If False, may use reference.
)
```

2. From a List of Dictionaries

In [4]:
data = [
    {'Name': 'Amit', 'Age': 25, 'City': 'Mumbai'},
    {'Name': 'Anand', 'Age': 28, 'City': 'Delhi'},
    {'Name': 'Akash', 'Age': 30, 'City': 'Patna'}
]
print(data)
df = pd.DataFrame(data)
print(df)

[{'Name': 'Amit', 'Age': 25, 'City': 'Mumbai'}, {'Name': 'Anand', 'Age': 28, 'City': 'Delhi'}, {'Name': 'Akash', 'Age': 30, 'City': 'Patna'}]
    Name  Age    City
0   Amit   25  Mumbai
1  Anand   28   Delhi
2  Akash   30   Patna

**3. From a List of Lists(With column names)**

In [5]:
data = [
    ['Amit', 25, 'Mumbai'],
    ['Anand', 28, 'Delhi'],
    ['Akash', 30, 'Patna']
]
df = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
print(df)

    Name  Age    City
0   Amit   25  Mumbai
1  Anand   28   Delhi
2  Akash   30   Patna

4. From a numpy array

In [6]:
arr = np.array([
    ['Amit', 25, 'Mumbai'],
    ['Anand', 28, 'Delhi'],
    ['Akash', 30, 'Patna']
])

In [7]:
arr

array([['Amit', '25', 'Mumbai'],
       ['Anand', '28', 'Delhi'],
       ['Akash', '30', 'Patna']], dtype='<U21')

In [8]:
df = pd.DataFrame(arr, columns=['Name', 'Age', 'City'])
print(df)

    Name Age    City
0   Amit  25  Mumbai
1  Anand  28   Delhi
2  Akash  30   Patna

5. From Series objects

In [9]:
name = pd.Series(['Amit', 'Anand', 'Akash'])
age = pd.Series([25, 28, 30])
city = pd.Series(['Mumbai', 'Delhi', 'Patna'])

In [11]:
df = pd.DataFrame({
    "Name" : name,
    "Age" : age,
    "City" : city
})
df

    Name  Age    City
0   Amit   25  Mumbai
1  Anand   28   Delhi
2  Akash   30   Patna

6. From a csv / Excel file

In [12]:
# Csv
df = pd.read_csv("data/dummy_data_csv.csv")
df.head()

      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000

In [ ]:
# tsv
df = pd.read_csv("data/dummy_data_tsv.tsv", sep='\t')
df.head()

      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000

In [15]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

In [16]:
# excel
df = pd.read_excel("data/dummy_data_excel.xlsx")
df.head()

      Name  Age     City  Salary
0     Amit   25    Patna   70000
1    Akash   30  Lucknow   80000
2     Aman   35    Delhi   75000
3   Manish   28   Jaipur   72000
4  Peeyush   32   Ranchi   78000

7. From a Url

In [17]:
# CSV
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
# JSON
url = "https://jsonplaceholder.typicode.com/users"
df = pd.read_json(url)
df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [20]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.3-cp312-cp312-win_amd64.whl.metadata (3.4 kB)
Downloading lxml-6.1.3-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.1 MB/s eta 0:00:04
   ---------- ----------------------------- 1.0/4.0 MB 1.7 MB/s eta 0:00:02
   ------------- -------------------------- 1.3/4.0 MB 1.9 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 2.1 MB/s eta 0:00:01
   ----------------------- ---------------- 2.4/4.0 MB 2.2 MB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 2.2 MB/s eta 0:00:01
   ---------------------------------- ----- 3.4/4.0 MB 2.2 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 2.1 MB/s  0:00:02
Installing collected packages: lxml
Successfully installed lxml-6.1.3

In [29]:
# HTML => Automatically extracts tables from HTML pages;
# Returns a list of DataFrames for all tables found

url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list"

tables = pd.read_html(url)

len(tables)

1

In [33]:
tables[0].head()

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550

**3. DataFrame Internal: Why Pandas DataFrames are so powerful?**
```text
Pandas DataFrames are powerful because they combine high-level usability with low-level, highly optimized data structures.
```
1. Foundation: NumPy Arrays for Speed

- Most Pandas data is stored in NumPy ndarray objects.
- NumPy arrays are contiguous memory blocks of homogeneous data → very fast to access and process.
- Operations are vectorized, running in compiled C code instead of Python loops.

In [34]:
data = {
    "Name" : ["Amit", "Anand", "Akash"],
    "Age"  : [25, 28 , 30],
    "CIty" : ["Mumbai", 'Delhi', "Patna"]
}
df = pd.DataFrame(data)

In [35]:
print(type(df["Name"]))

<class 'pandas.Series'>

In [43]:
df["Age"]

0    25
1    28
2    30
Name: Age, dtype: int64

In [42]:
type(df["Age"].values)

numpy.ndarray

In [41]:
df["Age"] + df["Age"]

0    50
1    56
2    60
Name: Age, dtype: int64


Why use NumPy under the hood?
- Speed – Vectorized operations are much faster than Python loops.
- Memory efficiency – NumPy arrays store data more compactly than Python lists.
- Interoperability – Easy to use NumPy’s mathematical and statistical functions directly on DataFrames.

**2. Columnar Storage**

* DataFrames store data column-wise, not row-wise.
* Benefits:
    * Fast column selection (just a pointer, no copying).
    * Efficient for analytical workloads (like SQL databases).
    * Compression works better because similar data is in one column.

**3. ArrayManager**

- Groups columns of the same dtype together in blocks for efficiency.
- Allows mixed types in the same DataFrame without losing speed for same-type columns.

**4. Label-aware Indexing**

* DataFrames have indexes for rows and columns.
* Indexes allow:
    * Fast lookups by label.
    * Automatic alignment of data during operations.

In [46]:
data = {
    "Name" : ["Amit", "Anand", "Akash"],
    "Age"  : [25, 28 , 30],
    "CIty" : ["Mumbai", 'Delhi', "Patna"]
}
df = pd.DataFrame(data, index=data['Name'])
df

        Name  Age    CIty
Amit    Amit   25  Mumbai
Anand  Anand   28   Delhi
Akash  Akash   30   Patna

In [47]:
df.loc["Anand"]

Name    Anand
Age        28
CIty    Delhi
Name: Anand, dtype: object

In [48]:
# When performing operations between Series or DataFrames, Pandas aligns data automatically by index.
s1 = pd.Series([100, 200, 300], index=['a', 'b', 'c'])
s2 = pd.Series([1, 2, 3], index=['b', 'c', 'd'])
print(s1)
print(s2)

a    100
b    200
c    300
dtype: int64
b    1
c    2
d    3
dtype: int64

In [49]:
s1+s2 # If an index exists in one Series but not the other, result is NaN.

a      NaN
b    201.0
c    302.0
d      NaN
dtype: float64

**5. C & Cython Acceleration**

- Many Pandas functions are written in Cython or directly in C.
- This allows operations on millions of rows to remain interactive and fast.

**6. Rich Metadata & Methods**

* Tracks column names, dtypes, missing values, categories, etc.
* Built-in methods include:
    - Reshaping (pivot, melt)
    - Grouping (groupby)
    - Joins/merges (SQL-like)
    - Time series handling