### Basic Operations on DataFrame

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Series
s = pd.Series([10,20,30,40], index=["a","b","c","d"])
print(s)

a    10
b    20
c    30
d    40
dtype: int64

In [3]:
# DataFrame
data = {
    "UID": [101, 201, 401],
    "Name": ["Amit", "Anand", "Akash"],
    "Age" : [25, 28, 30],
    "City" : ["Mumbai", "Delhi", "Patna"]
}
df = pd.DataFrame(data)
print(df)

   UID   Name  Age    City
0  101   Amit   25  Mumbai
1  201  Anand   28   Delhi
2  401  Akash   30   Patna

In [4]:
# Print at max top 5 rows of dataframe
df.head()

   UID   Name  Age    City
0  101   Amit   25  Mumbai
1  201  Anand   28   Delhi
2  401  Akash   30   Patna

In [5]:
# bottom 5 rows
df.tail()

   UID   Name  Age    City
0  101   Amit   25  Mumbai
1  201  Anand   28   Delhi
2  401  Akash   30   Patna

In [6]:
# Shape of dataframe
df.shape

(3, 4)

In [7]:
# len
len(df)

3

**Pandas datatype**

In [8]:
df.head()

   UID   Name  Age    City
0  101   Amit   25  Mumbai
1  201  Anand   28   Delhi
2  401  Akash   30   Patna

In [9]:
# dataframe datatypes
df.dtypes

UID     int64
Name      str
Age     int64
City      str
dtype: object

In [10]:
# reduce memory consumed for Age atribue
df["Age"] = df["Age"].astype("int32")
df.dtypes

UID     int64
Name      str
Age     int32
City      str
dtype: object

*Note*
- in a pandas dataframe, if a column contains strings, Pandas sets its dtype to object
- object is basically a generic python object type, which can hold anything- string , lists, or even mixed types.
- strings with pandas 1.0, there is a dedicaed string dtype(string) you can use

In [11]:
df["City"]= df["City"].astype("object")
df.dtypes

UID      int64
Name       str
Age      int32
City    object
dtype: object

In [12]:
# basic dataframe of info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   UID     3 non-null      int64
 1   Name    3 non-null      str
 2   Age     3 non-null      int32
 3   City    3 non-null      object
dtypes: int32(1), int64(1), object(1), str(1)
memory usage: 216.0+ bytes

**Index, Columns and Labels in dataframe**

In [13]:
# columns attribute/property
df.columns

Index(['UID', 'Name', 'Age', 'City'], dtype='str')

In [14]:
df.index

RangeIndex(start=0, stop=3, step=1)

In a DataFrame:

- Index → The row labels of the DataFrame. By default, pandas assigns `0, 1, 2, ...` as the index.
- Columns → The labels for each vertical series in the DataFrame.
- Labels → Identifiers for both rows (index) and columns. They are commonly used with `.loc`.

| Component | Description | Example |
|---|---|---|
| Index | Row labels | `0, 1, 2` or custom |
| Columns | Column labels | `"Name"`, `"Age"`, `"City"` |
| Labels | Identifiers for rows/columns | Used in `.loc` |

In [15]:
from numpy.random import randint as ri
matrix_data = ri(1,100,20).reshape(5,4)
matrix_data

array([[59, 28, 70, 10],
       [ 1, 84, 42,  8],
       [97, 78, 15, 35],
       [87, 90, 62, 92],
       [22, 56, 27, 18]], dtype=int32)

In [16]:
row_labels = ["A","B","C","D","E"]
column_headings = ["W","X","Y","Z"]
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
df

    W   X   Y   Z
A  59  28  70  10
B   1  84  42   8
C  97  78  15  35
D  87  90  62  92
E  22  56  27  18

In [17]:
df.shape

(5, 4)

In [18]:
df.info()

<class 'pandas.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   W       5 non-null      int32
 1   X       5 non-null      int32
 2   Y       5 non-null      int32
 3   Z       5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes

In [19]:
df.describe()

               W          X          Y          Z
count   5.000000   5.000000   5.000000   5.000000
mean   53.200000  67.200000  43.200000  32.600000
std    41.209222  25.400787  23.080295  34.868324
min     1.000000  28.000000  15.000000   8.000000
25%    22.000000  56.000000  27.000000  10.000000
50%    59.000000  78.000000  42.000000  18.000000
75%    87.000000  84.000000  62.000000  35.000000
max    97.000000  90.000000  70.000000  92.000000

The df.describe() function in Pandas is used to generate descriptive statistics of the DataFrame’s columns. It provides a quick summary of numerical and, optionally, categorical data.

In [20]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='str')

In [21]:
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='str')

In [22]:
df['W']

A    59
B     1
C    97
D    87
E    22
Name: W, dtype: int32

In [23]:
type(df["W"])

pandas.Series

In [24]:
# Access column X and Z
df[["X", "Z"]]

    X   Z
A  28  10
B  84   8
C  78  35
D  90  92
E  56  18

In [25]:
type(df[["X", "Z"]])

pandas.DataFrame

**Drop a row and columns**

In [26]:
# drop row
df.drop("A")

    W   X   Y   Z
B   1  84  42   8
C  97  78  15  35
D  87  90  62  92
E  22  56  27  18

In [27]:
# drop columns 
df.drop("X", axis=1, inplace=True)

In [28]:
df

    W   Y   Z
A  59  70  10
B   1  42   8
C  97  15  35
D  87  62  92
E  22  27  18

**Selecting/ indexing rows**
- Label-based `loc` method
- index(numeric) `iloc` method

In [29]:
df.head()

    W   Y   Z
A  59  70  10
B   1  42   8
C  97  15  35
D  87  62  92
E  22  27  18

In [35]:
# selecting row ith label - C or index 2 ==> subsetting
print(df.loc['C'])
print("-"*100)
print(df.iloc[2])

W    97
Y    15
Z    35
Name: C, dtype: int32
----------------------------------------------------------------------------------------------------
W    97
Y    15
Z    35
Name: C, dtype: int32

In [37]:
# Select multiple rows with label - "A" and "C" ==> Subsetting
print(df.loc[["A","C"]])

print("-"*100)

print(df.iloc[[0,2]])

    W   Y   Z
A  59  70  10
C  97  15  35
----------------------------------------------------------------------------------------------------
    W   Y   Z
A  59  70  10
C  97  15  35

In [40]:
# Slicing for multiple rows - first 3 rows ==> slicing
print(df.loc["A":"C"])
print("-"*100)
print(df.iloc[0:2])

    W   Y   Z
A  59  70  10
B   1  42   8
C  97  15  35
----------------------------------------------------------------------------------------------------
    W   Y   Z
A  59  70  10
B   1  42   8

**Subsetting Dataframe**
- subsetting refrers to filtering down the DataFrame. Selecting a subset of rows, columns, or both

In [41]:
df

    W   Y   Z
A  59  70  10
B   1  42   8
C  97  15  35
D  87  62  92
E  22  27  18

In [44]:
# Elemey at row "B" and column "Y" is
print(df.loc["B", "Y"])
print("-"*100)
print(df.iloc[1,1])

42
----------------------------------------------------------------------------------------------------
42

In [48]:
# subset comparising of rows B and C and column w and y
print(df.loc[["B","C"], ["W", "Y"]])
print("-"*100)
print(df.iloc[[1,2], [0,1]])

    W   Y
B   1  42
C  97  15
----------------------------------------------------------------------------------------------------
    W   Y
B   1  42
C  97  15

**Subsetting dataframe based on some conditon for cell**

In [51]:
# subsetting dataframe based on some condition - values > 40
bool_df = df > 40
bool_df

       W      Y      Z
A   True   True  False
B  False   True  False
C   True  False  False
D   True   True   True
E  False  False  False

In [52]:
df[bool_df]

      W     Y     Z
A  59.0  70.0   NaN
B   NaN  42.0   NaN
C  97.0   NaN   NaN
D  87.0  62.0  92.0
E   NaN   NaN   NaN

In [53]:
# conditional subsetting - one liner
df[df>40]

      W     Y     Z
A  59.0  70.0   NaN
B   NaN  42.0   NaN
C  97.0   NaN   NaN
D  87.0  62.0  92.0
E   NaN   NaN   NaN

In [75]:
# Creating a dataframe
# creating a dataframe
matrix_data = np.matrix('22,160,70;42,170,80;30,175,90;35,160,70;25,140,70')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight'] # 'Height(Cm)', 'Weight(Kg)

In [76]:
matrix_data

matrix([[ 22, 160,  70],
        [ 42, 170,  80],
        [ 30, 175,  90],
        [ 35, 160,  70],
        [ 25, 140,  70]])

In [77]:
df = pd.DataFrame(data =matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n","-"*25, sep="")
print(df)

A new DataFrame
-------------------------
   Age  Height  Weight
A   22     160      70
B   42     170      80
C   30     175      90
D   35     160      70
E   25     140      70

In [59]:
print("\nRows with height > 158cm\n", sep='')
print(df[df["Height"]> 158])

Rows with height > 158cm

   Age  Height  Weight
A   22     160      70
B   42     170      80
C   30     175      90
D   35     160      70

In [67]:
print("\nRows with height > 158 and weight > 70\n", sep="")
print("-"*50)
print(df[((df["Height"] > 158) & (df["Weight"] > 70))])

Rows with height > 158 and weight > 70

--------------------------------------------------
   Age  Height  Weight
B   42     170      80
C   30     175      90

**Reseting the index of your DataFrame**

In [70]:
# what are the index of df
df.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='str')

In [79]:
# Reset index, Try inplace =True
df.reset_index(drop=True, inplace=True)

In [80]:
df

   Age  Height  Weight
0   22     160      70
1   42     170      80
2   30     175      90
3   35     160      70
4   25     140      70

In [81]:
df = pd.DataFrame(data =matrix_data, index=row_labels, columns=column_headings)
print(df)

   Age  Height  Weight
A   22     160      70
B   42     170      80
C   30     175      90
D   35     160      70
E   25     140      70

In [82]:
# adding a row to a dataframe
df.loc["F"] = [22, 179, 72]
df

   Age  Height  Weight
A   22     160      70
B   42     170      80
C   30     175      90
D   35     160      70
E   25     140      70
F   22     179      72

In [85]:
# Add a new column BMI = weight(kg) / height(m)^2
df["BMI"] = df["Weight"] / (df["Height"] /100)**2
df

   Age  Height  Weight        BMI
A   22     160      70  27.343750
B   42     170      80  27.681661
C   30     175      90  29.387755
D   35     160      70  27.343750
E   25     140      70  35.714286
F   22     179      72  22.471209

In [89]:
# Setting "profession" column as index
df["Profession"] = "Student Teacher Engineer Doctor Nurse Student".split()
df

   Age  Height  Weight        BMI Profession
A   22     160      70  27.343750    Student
B   42     170      80  27.681661    Teacher
C   30     175      90  29.387755   Engineer
D   35     160      70  27.343750     Doctor
E   25     140      70  35.714286      Nurse
F   22     179      72  22.471209    Student

In [90]:
"Student Teacher Engineer Doctor Nurse Student".split()

['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse', 'Student']

**Rename the index of a dataframe**

In [91]:
df.set_index('Profession')

            Age  Height  Weight        BMI
Profession
Student      22     160      70  27.343750
Teacher      42     170      80  27.681661
Engineer     30     175      90  29.387755
Doctor       35     160      70  27.343750
Nurse        25     140      70  35.714286
Student      22     179      72  22.471209

**renamne index**

In [92]:
df

   Age  Height  Weight        BMI Profession
A   22     160      70  27.343750    Student
B   42     170      80  27.681661    Teacher
C   30     175      90  29.387755   Engineer
D   35     160      70  27.343750     Doctor
E   25     140      70  35.714286      Nurse
F   22     179      72  22.471209    Student

In [93]:
df.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')

In [96]:
# rename index
df.index = ["a","b","c","d","e","f"]
df

   Age  Height  Weight        BMI Profession
a   22     160      70  27.343750    Student
b   42     170      80  27.681661    Teacher
c   30     175      90  29.387755   Engineer
d   35     160      70  27.343750     Doctor
e   25     140      70  35.714286      Nurse
f   22     179      72  22.471209    Student

**Rename the columns of a DataFrame**

In [97]:
df.columns

Index(['Age', 'Height', 'Weight', 'BMI', 'Profession'], dtype='str')

In [ ]:
# rename the columns
df.columns = ['age', 'height', 'weight', 'bmi', 'profession']
df

   age  height  weight        bmi profession
a   22     160      70  27.343750    Student
b   42     170      80  27.681661    Teacher
c   30     175      90  29.387755   Engineer
d   35     160      70  27.343750     Doctor
e   25     140      70  35.714286      Nurse
f   22     179      72  22.471209    Student