In [1]:
# import
import numpy as np
import pandas as pd

**Apply() method**

In [2]:
# Create demo DataFrame with real-looking model names and metrics
data = {
    "model_name": [
        "Logistic Regression", 
        "Decision Tree", 
        "Random Forest", 
        "XGBoost", 
        "LightGBM", 
        "KNN", 
        "Naive Bayes", 
        "SVM", 
        "CNN", 
        "LSTM"
    ],
    "execution_time": [0.5, 0.8, 2.3, 3.1, 2.8, 1.2, 0.6, 1.9, 4.5, 5.0],  # seconds
    "model_size": [2.3, 5.6, 45.2, 60.1, 55.8, 8.4, 1.2, 12.3, 120.5, 150.7],  # MB
    "accuracy": [0.82, 0.78, 0.89, 0.91, 0.90, 0.76, 0.74, 0.88, 0.93, 0.92],
    "f1_score": [0.80, 0.75, 0.87, 0.90, 0.89, 0.74, 0.72, 0.86, 0.92, 0.91],
    "precision": [0.81, 0.76, 0.88, 0.91, 0.90, 0.75, 0.73, 0.87, 0.93, 0.92],
    "recall": [0.79, 0.74, 0.86, 0.89, 0.88, 0.73, 0.71, 0.85, 0.91, 0.90],
}

In [3]:
# create a dataframe
df = pd.DataFrame(data)
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   model_name      10 non-null     str
 1   execution_time  10 non-null     float64
 2   model_size      10 non-null     float64
 3   accuracy        10 non-null     float64
 4   f1_score        10 non-null     float64
 5   precision       10 non-null     float64
 6   recall          10 non-null     float64
dtypes: float64(6), str(1)
memory usage: 692.0 bytes

**Apply user defined Funcations**

In [5]:
# convert model name to lowercase and space by underscore
def testfunc(x):
    model_name = "_".join(x.split())
    model_name = model_name.lower()
    return model_name

In [7]:
# convert model name to lowercase and space by underscore
df["model_name"].apply(testfunc)

0    logistic_regression
1          decision_tree
2          random_forest
3                xgboost
4               lightgbm
5                    knn
6            naive_bayes
7                    svm
8                    cnn
9                   lstm
Name: model_name, dtype: str

In [8]:
df.head()

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88

In [9]:
# using map() instead of apply()
df["model_name"].map(testfunc)

0    logistic_regression
1          decision_tree
2          random_forest
3                xgboost
4               lightgbm
5                    knn
6            naive_bayes
7                    svm
8                    cnn
9                   lstm
Name: model_name, dtype: str

**Apply vs map**
- .map()--> works only on Series element wise
- .apply() --> works on series or dataframe, more flexiable(row/ column-wise)

In [11]:
df.head()

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88

In [12]:
# convert exceution time from second to milli-second using apply
df["execution_time"].apply(lambda x: x*1000)

0     500.0
1     800.0
2    2300.0
3    3100.0
4    2800.0
5    1200.0
6     600.0
7    1900.0
8    4500.0
9    5000.0
Name: execution_time, dtype: float64

In [14]:
df["execution_time"].map(lambda x: x*1000)

0     500.0
1     800.0
2    2300.0
3    3100.0
4    2800.0
5    1200.0
6     600.0
7    1900.0
8    4500.0
9    5000.0
Name: execution_time, dtype: float64

In [15]:
df.head()

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88

In [16]:
# model_score = 0.8*f1_score + 0.1*(1/execution_time) + 0.1*(1/model_size)
df["model_score"] = (
    0.8 * df["f1_score"] +
    0.1 * (1 / df["execution_time"]) +
    0.1 * (1 / df["model_size"])
)

In [18]:
df

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73,0.687238
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71,0.826000
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85,0.748762
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91,0.759052
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90,0.748664

Even though Random Forest model have high f1 score than decision tree, the overall score for RF is less than DT

**Apply built in Funcations**

In [21]:
# calculating length of model name string
df['len_model_name'] = df['model_name'].apply(len)

In [22]:
df.head()

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score,len_model_name
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478,19
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857,13
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691,13
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922,7
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506,8

In [23]:
# Calcularte sqrt of precisiom
import math
df["precision"].apply(math.sqrt)

0    0.900000
1    0.871780
2    0.938083
3    0.953939
4    0.948683
5    0.866025
6    0.854400
7    0.932738
8    0.964365
9    0.959166
Name: precision, dtype: float64

In [28]:
# sort values based on score
df.sort_values(by='model_score', ascending=False)

,model_name,execution_time,model_size,accuracy,f1_score,precision,recall,model_score,len_model_name
0,Logistic Regression,0.5,2.3,0.82,0.80,0.81,0.79,0.883478,19
6,Naive Bayes,0.6,1.2,0.74,0.72,0.73,0.71,0.826000,11
8,CNN,4.5,120.5,0.93,0.92,0.93,0.91,0.759052,3
3,XGBoost,3.1,60.1,0.91,0.90,0.91,0.89,0.753922,7
4,LightGBM,2.8,55.8,0.90,0.89,0.90,0.88,0.749506,8
7,SVM,1.9,12.3,0.88,0.86,0.87,0.85,0.748762,3
9,LSTM,5.0,150.7,0.92,0.91,0.92,0.90,0.748664,4
1,Decision Tree,0.8,5.6,0.78,0.75,0.76,0.74,0.742857,13
2,Random Forest,2.3,45.2,0.89,0.87,0.88,0.86,0.741691,13
5,KNN,1.2,8.4,0.76,0.74,0.75,0.73,0.687238,3

**Date & Time**

- In Pandas, datetime columns(Timestamp) is used to represent dates and times in a standardized format, which allows easy filtering, arithmetic, and plotting.
- Very useful data-type and also used in timeseries data.
- Benefits of datetime dtype : Easy filtering, Arithmetic, Extract components and Time Series opearations

pandas.Timestamp():

1. Constructor for a single timestamp object.(like Python’s datetime, but with more Pandas power).
2. Input: A string, datetime, or numeric value.
3. Output: A Timestamp object.
4. Best for: Working with one specific date/time.

In [33]:
# Create a Range of Dates
ts1 = pd.Timestamp("2025-08-18 14:30:15") # <class 'pandas._libs.tslibs.timestamps.Timestamp'>
ts2 = pd.Timestamp("2025-08-18")
ts3 = pd.Timestamp("18-08-2025")
ts4 = pd.Timestamp(year=2025, month=8, day=18, hour=14, minute=30, second=15)
print(ts1,"\n", ts2,"\n", ts3, "\n", ts4)
print(type(ts1),"\n", type(ts2),"\n", type(ts3),"\n", type(ts4))

2025-08-18 14:30:15
 2025-08-18 00:00:00
 2025-08-18 00:00:00
 2025-08-18 14:30:15
<class 'pandas.Timestamp'>
 <class 'pandas.Timestamp'>
 <class 'pandas.Timestamp'>
 <class 'pandas.Timestamp'>

pandas.to_datetime():
Purpose: Converts many kinds of inputs (strings, lists, arrays, Series, dict) into datetime-like values.
Input: Scalar (one value) OR iterable (list, Series).
Output: Timestamp (if scalar input), DatetimeIndex (if list/array input), Series of datetime64 (if Series input).
Best for: Parsing existing data into datetime format.
DatetimeIndex - a sequence of Timestamps that can be used as an index for time series data.