In [138]:
import pandas as pd

#### Series
- A Series is a one-dimensional labeled array.
- `values`: The actual data stores in the series
- `index`: The label associated with each data point

In [139]:
welcome_series = pd.Series(["Welcome", "to", "CS 189"])
welcome_series

0    Welcome
1         to
2     CS 189
dtype: str

In [140]:
# values
welcome_series.values

<StringArray>
['Welcome', 'to', 'CS 189']
Length: 3, dtype: str

In [141]:
# index
welcome_series.index

RangeIndex(start=0, stop=3, step=1)

##### DataFrame

**Creating a Dataframe**

In [142]:
data = {
    'Landmark': ['Sather Gate', 'Campanile', 'Doe Library', 'Memorial Glade', 'Sproul Plaza'],
    'Type': ['Gate', 'Tower', 'Library', 'Open Space', 'Plaza'],
    'Height': [30, 307, 80, 0, 0],
    'Year Built': [1910, 1914, 1911, None, 1962]
}

df = pd.DataFrame(data)
df

         Landmark        Type  Height  Year Built
0     Sather Gate        Gate      30      1910.0
1       Campanile       Tower     307      1914.0
2     Doe Library     Library      80      1911.0
3  Memorial Glade  Open Space       0         NaN
4    Sproul Plaza       Plaza       0      1962.0

##### Untility Funcations for DataFrame

In [143]:
# first few rows
df.head() # default is 5

         Landmark        Type  Height  Year Built
0     Sather Gate        Gate      30      1910.0
1       Campanile       Tower     307      1914.0
2     Doe Library     Library      80      1911.0
3  Memorial Glade  Open Space       0         NaN
4    Sproul Plaza       Plaza       0      1962.0

In [144]:
# Last few rows
df.tail()

         Landmark        Type  Height  Year Built
0     Sather Gate        Gate      30      1910.0
1       Campanile       Tower     307      1914.0
2     Doe Library     Library      80      1911.0
3  Memorial Glade  Open Space       0         NaN
4    Sproul Plaza       Plaza       0      1962.0

In [145]:
# shape
df.shape

(5, 4)

In [146]:
# size
df.size

20

In [147]:
# random selection of rows from a dataframe
df.sample(n= 5)

         Landmark        Type  Height  Year Built
2     Doe Library     Library      80      1911.0
0     Sather Gate        Gate      30      1910.0
1       Campanile       Tower     307      1914.0
4    Sproul Plaza       Plaza       0      1962.0
3  Memorial Glade  Open Space       0         NaN

In [148]:
# randomly sample frac of rows
df.sample(frac= 0.1)

Empty DataFrame
Columns: [Landmark, Type, Height, Year Built]
Index: []

In [149]:
# Allow the same row to appear multiple times
df.sample(n= 3, replace=True)

       Landmark   Type  Height  Year Built
4  Sproul Plaza  Plaza       0      1962.0
0   Sather Gate   Gate      30      1910.0
4  Sproul Plaza  Plaza       0      1962.0

In [150]:
# Using random_state for reproducibility
df.sample(n= 3, random_state=42)

       Landmark     Type  Height  Year Built
1     Campanile    Tower     307      1914.0
4  Sproul Plaza    Plaza       0      1962.0
2   Doe Library  Library      80      1911.0

In [151]:
# Values_Counts()
type_counts = df["Type"].value_counts()
type_counts

Type
Gate          1
Tower         1
Library       1
Open Space    1
Plaza         1
Name: count, dtype: int64

In [152]:
type_counts = df["Type"].unique()
type_counts

<StringArray>
['Gate', 'Tower', 'Library', 'Open Space', 'Plaza']
Length: 5, dtype: str

**Integer-based Extraction: iloc[]**

In [153]:
df.iloc[[1,2]]

      Landmark     Type  Height  Year Built
1    Campanile    Tower     307      1914.0
2  Doe Library  Library      80      1911.0

In [154]:
df.iloc[[1,2],[1,2,3]]

      Type  Height  Year Built
1    Tower     307      1914.0
2  Library      80      1911.0

In [155]:
df.iloc[2:4]

         Landmark        Type  Height  Year Built
2     Doe Library     Library      80      1911.0
3  Memorial Glade  Open Space       0         NaN

In [156]:
df.iloc[:,1:2]

         Type
0        Gate
1       Tower
2     Library
3  Open Space
4       Plaza

In [157]:
df.iloc[:,0]

0       Sather Gate
1         Campanile
2       Doe Library
3    Memorial Glade
4      Sproul Plaza
Name: Landmark, dtype: str

In [158]:
df.iloc[2]

Landmark      Doe Library
Type              Library
Height                 80
Year Built         1911.0
Name: 2, dtype: object

In [159]:
df.iloc[1,2]

np.int64(307)

**Label-based Extraction: Loc[]**

In [160]:
df.loc[[1,2]]

      Landmark     Type  Height  Year Built
1    Campanile    Tower     307      1914.0
2  Doe Library  Library      80      1911.0

In [161]:
df.loc[[1,2],['Type','Height','Year Built']]

      Type  Height  Year Built
1    Tower     307      1914.0
2  Library      80      1911.0

In [162]:
df.loc[2:3]

         Landmark        Type  Height  Year Built
2     Doe Library     Library      80      1911.0
3  Memorial Glade  Open Space       0         NaN

In [163]:
df.loc[:, "Landmark":"Height"]

         Landmark        Type  Height
0     Sather Gate        Gate      30
1       Campanile       Tower     307
2     Doe Library     Library      80
3  Memorial Glade  Open Space       0
4    Sproul Plaza       Plaza       0

**Context-Dependent Selection**

In [164]:
df[["Landmark","Year Built"]]

         Landmark  Year Built
0     Sather Gate      1910.0
1       Campanile      1914.0
2     Doe Library      1911.0
3  Memorial Glade         NaN
4    Sproul Plaza      1962.0

In [165]:
df["Year Built"]

0    1910.0
1    1914.0
2    1911.0
3       NaN
4    1962.0
Name: Year Built, dtype: float64

##### Filtering

In [167]:
df["Height"] > 50  # Boolean Series

0    False
1     True
2     True
3    False
4    False
Name: Height, dtype: bool

In [169]:
df.loc[df["Height"] > 50]

      Landmark     Type  Height  Year Built
1    Campanile    Tower     307      1914.0
2  Doe Library  Library      80      1911.0

In [170]:
df.loc[(df["Height"] > 50) & (df["Type"]=="Library")]

      Landmark     Type  Height  Year Built
2  Doe Library  Library      80      1911.0

##### Modification

In [172]:
df["Experience"] = [2,5,1,8,4]
df.head()

         Landmark        Type  Height  Year Built  Experience
0     Sather Gate        Gate      30      1910.0           2
1       Campanile       Tower     307      1914.0           5
2     Doe Library     Library      80      1911.0           1
3  Memorial Glade  Open Space       0         NaN           8
4    Sproul Plaza       Plaza       0      1962.0           4

In [174]:
df["Height_Increase"] = df['Height'] * 0.1
df.head()

         Landmark        Type  Height  Year Built  Experience  Height_Increase
0     Sather Gate        Gate      30      1910.0           2              3.0
1       Campanile       Tower     307      1914.0           5             30.7
2     Doe Library     Library      80      1911.0           1              8.0
3  Memorial Glade  Open Space       0         NaN           8              0.0
4    Sproul Plaza       Plaza       0      1962.0           4              0.0

**Dropping a column**

In [175]:
df.drop(columns=["Experience"])

         Landmark        Type  Height  Year Built  Height_Increase
0     Sather Gate        Gate      30      1910.0              3.0
1       Campanile       Tower     307      1914.0             30.7
2     Doe Library     Library      80      1911.0              8.0
3  Memorial Glade  Open Space       0         NaN              0.0
4    Sproul Plaza       Plaza       0      1962.0              0.0

In [176]:
df

         Landmark        Type  Height  Year Built  Experience  Height_Increase
0     Sather Gate        Gate      30      1910.0           2              3.0
1       Campanile       Tower     307      1914.0           5             30.7
2     Doe Library     Library      80      1911.0           1              8.0
3  Memorial Glade  Open Space       0         NaN           8              0.0
4    Sproul Plaza       Plaza       0      1962.0           4              0.0

In [177]:
df.drop(columns=["Experience"], inplace=True)
df.head()

         Landmark        Type  Height  Year Built  Height_Increase
0     Sather Gate        Gate      30      1910.0              3.0
1       Campanile       Tower     307      1914.0             30.7
2     Doe Library     Library      80      1911.0              8.0
3  Memorial Glade  Open Space       0         NaN              0.0
4    Sproul Plaza       Plaza       0      1962.0              0.0

#####  Sorting DataFrame

In [178]:
df.sort_values(by='Height', ascending=True)

         Landmark        Type  Height  Year Built  Height_Increase
3  Memorial Glade  Open Space       0         NaN              0.0
4    Sproul Plaza       Plaza       0      1962.0              0.0
0     Sather Gate        Gate      30      1910.0              3.0
2     Doe Library     Library      80      1911.0              8.0
1       Campanile       Tower     307      1914.0             30.7

In [179]:
df.sort_values(by=['Height', "Type"], ascending=True)

         Landmark        Type  Height  Year Built  Height_Increase
3  Memorial Glade  Open Space       0         NaN              0.0
4    Sproul Plaza       Plaza       0      1962.0              0.0
0     Sather Gate        Gate      30      1910.0              3.0
2     Doe Library     Library      80      1911.0              8.0
1       Campanile       Tower     307      1914.0             30.7

##### Handling Missing values

In [181]:
# detect misisng values
df.isna().sum()

Landmark           0
Type               0
Height             0
Year Built         1
Height_Increase    0
dtype: int64

In [182]:
# drop misisng values
df.dropna()

       Landmark     Type  Height  Year Built  Height_Increase
0   Sather Gate     Gate      30      1910.0              3.0
1     Campanile    Tower     307      1914.0             30.7
2   Doe Library  Library      80      1911.0              8.0
4  Sproul Plaza    Plaza       0      1962.0              0.0

**Imputation**

In [183]:
df.fillna(0)

         Landmark        Type  Height  Year Built  Height_Increase
0     Sather Gate        Gate      30      1910.0              3.0
1       Campanile       Tower     307      1914.0             30.7
2     Doe Library     Library      80      1911.0              8.0
3  Memorial Glade  Open Space       0         0.0              0.0
4    Sproul Plaza       Plaza       0      1962.0              0.0

##### Aggregating data

In [184]:
df["Height"].mean()

np.float64(83.4)

In [185]:
df["Height"].std()

np.float64(129.2006191935627)