### Know your data
**Research Question:** Are property prices in Mexico more influenced by property
size or by location?

In [61]:
# Import pandas for data manipulation
import pandas as pd

In [62]:
# Define the path to our data file
path_1 = "./data/mexico-real-estate-1.csv"

**Loading the data**

In [63]:
(
    pd.read_csv(path_1)
)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"
...,...,...,...,...,...,...
695,house,Morelos,NaN,NaN,310.0,"$237,089.17"
696,house,Yucatán,21.050653,-89.558841,334.0,"$137,017.34"
697,house,Yucatán,21.343796,-89.262060,130.0,"$110,404.35"
698,apartment,Nuevo León,NaN,NaN,155.0,"$184,446.42"
699,house,Querétaro,20.587378,-100.418361,106.0,"$56,637.97"

**Inspecting the Data: The Five-Method Ritual**

**Step 1: .head() --> first 5 rows**

In [64]:
(
    pd.read_csv(path_1)
    .head()
)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
4,house,Veracruz de Ignacio de la Llave,NaN,NaN,175.0,"$94,835.67"

Initial observations

- price_usd is stored as text and needs numeric conversion.
- lat and lon contain missing values.

**Step 2: .shape — how large is this DataFrame exactly?**

In [65]:
(
    pd.read_csv(path_1)
    .shape
)

(700, 6)

700 rows and 6 columns.

**Step 3: .info() — information about the data**

In [66]:
(
    pd.read_csv(path_1)
    .info()
)

<class 'pandas.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  700 non-null    str
 1   state          700 non-null    str
 2   lat            583 non-null    float64
 3   lon            583 non-null    float64
 4   area_m2        700 non-null    float64
 5   price_usd      700 non-null    str
dtypes: float64(3), str(3)
memory usage: 32.9 KB

Shows row count, column types, non-null values, and memory usage.

**Step 4: .dtypes --> clear picture of data types of columns**

In [67]:
(
    pd.read_csv(path_1)
    .dtypes
)

property_type        str
state                str
lat              float64
lon              float64
area_m2          float64
price_usd            str
dtype: object

**Step 5: .isnull().sum() --> missing values**

In [68]:
(
    pd.read_csv(path_1)
    .isnull()
    .sum()
)

property_type      0
state              0
lat              117
lon              117
area_m2            0
price_usd          0
dtype: int64

In [69]:
#  Drop missing values
(
    pd.read_csv(path_1)
    .dropna()
)

,property_type,state,lat,lon,area_m2,price_usd
0,house,Estado de México,19.560181,-99.233528,150.0,"$67,965.56"
1,house,Nuevo León,25.688436,-100.198807,186.0,"$63,223.78"
2,apartment,Guerrero,16.767704,-99.764383,82.0,"$84,298.37"
3,apartment,Guerrero,16.829782,-99.911012,150.0,"$94,308.80"
5,house,Yucatán,21.052583,-89.538639,205.0,"$105,191.37"
...,...,...,...,...,...,...
693,house,Puebla,19.051815,-98.277669,198.0,"$115,910.26"
694,apartment,Distrito Federal,19.309208,-99.171906,70.0,"$77,572.89"
696,house,Yucatán,21.050653,-89.558841,334.0,"$137,017.34"
697,house,Yucatán,21.343796,-89.262060,130.0,"$110,404.35"
699,house,Querétaro,20.587378,-100.418361,106.0,"$56,637.97"

In [70]:
df1 = (
    pd.read_csv(path_1)
    .dropna()
    .assign(
        price_usd = lambda x : x["price_usd"]
        .str.replace("$","",regex=False)
        .str.replace(",","",regex=False)
        .astype(float)
    )
)

In [71]:
path_2 = "./data/mexico-real-estate-2.csv"
path_3 = "./data/mexico-real-estate-3.csv"

In [72]:
df2 = (
    pd.read_csv(path_2)
    .dropna()
    .assign(
        price_usd = lambda x : x['price_mxn'] /19
    )
    .drop("price_mxn", axis=1)
)
print(f"df2 type: {type(df2)}")
print(f"df2 shape: {df2.shape}")
df2.head()

df2 type: <class 'pandas.DataFrame'>
df2 shape: (571, 6)

,property_type,state,lat,lon,area_m2,price_usd
0,apartment,Nuevo León,25.721081,-100.345581,72.0,68421.052632
2,house,Morelos,23.634501,-102.552788,360.0,278947.368421
6,apartment,Estado de México,19.272040,-99.572013,85.0,65789.473684
7,house,San Luis Potosí,22.138882,-100.996510,158.0,111578.947368
8,apartment,Distrito Federal,19.394558,-99.129707,65.0,39904.736842

In [87]:
df3 = (
    pd.read_csv(path_3)
    .assign(
        lat = lambda x: x["lat-lon"]
        .str.split(",",expand=True)[0]
        .astype(float),
        lon = lambda x : x['lat-lon']
        .str.split(",", expand=True)[1]
        .astype(float),
        state = lambda x : x["place_with_parent_names"]
        .str.split("|",expand=True)[2]
        
    )
    .drop(["place_with_parent_names","lat-lon"], axis=1)
)
print(f"df3 type: {type(df3)}")
print(f"df3 shape: {df3.shape}")
df3.head()

df3 type: <class 'pandas.DataFrame'>
df3 shape: (700, 6)

,property_type,area_m2,price_usd,lat,lon,state
0,apartment,71.0,48550.59,19.525890,-99.151703,Distrito Federal
1,house,233.0,168636.73,19.264054,-99.572753,Estado de México
2,house,300.0,86932.69,19.268629,-99.671722,Estado de México
3,house,275.0,263432.41,NaN,NaN,Morelos
4,apartment,84.0,68508.67,19.511938,-96.871956,Veracruz de Ignacio de la Llave

In [88]:
# Check if all column sets are identical
columns_match = set(df1) == set(df2) == set(df3)

if columns_match:
    print("All DataFrames have the same columns.")
else:
    print("Column mismatch detected!")
    # Optional: See the difference
    print("df1 vs df2 diff:", set(df1.columns) ^ set(df2.columns))
    print("df2 vs df3 diff:", set(df2.columns) ^ set(df3.columns))

All DataFrames have the same columns.

In [90]:
# Stack df1, df2, and df3 vertically
df = pd.concat([df1, df2, df3], ignore_index=True)
df.shape

(1854, 6)

In [91]:
# Save your cleaned combined dataset
df.to_csv("./data/mexico-real-estate-combined-clean.csv", index=False)

**Descriptive Statistics**

In [94]:
# Summarize the numeric columns
summary = df[["price_usd", "area_m2"]].describe()

# Format for readability
pd.options.display.float_format = '{:,.2f}'.format

summary

       price_usd  area_m2
count   1,854.00 1,854.00
mean  116,892.83   171.59
std    66,462.05    80.48
min    33,157.89    60.00
25%    65,789.47   102.25
50%   100,000.00   160.00
75%   152,790.80   220.00
max   326,733.66   385.00

Reading `.describe()` 

price_usd

* Count: Should be ~1,700+; lower means some prices are still NaN.
* Mean > Median: Indicates right skew; expensive properties pull the mean upward.
* Std: High variation means price depends on factors like location, area, and property type.
* Min/Max: Check for suspicious values or genuine luxury properties.

area_m2

* Also likely right-skewed: most properties are smaller, with a few very large ones.
* IQR = Q3 − Q1: Shows the middle 50% of properties.

For our research question

Since we're comparing prices across states, median is the better primary measure because it is less affected by extreme luxury properties.

What `.describe()` cannot show

* Distribution shape or multiple peaks
* Where outliers occur
* Price–area relationship
* Geographic patterns

Visualization will reveal these patterns more clearly.