### Duplicate rows

In [1]:
import pandas as pd

In [2]:
# read a dataset of movie reviewers into a DataFrame
user_cols = ['user_id', 'age', 'gender', 'occupation', 'zip_code']
users = pd.read_table('http://bit.ly/movieusers', sep='|', header=None, names=user_cols, index_col='user_id')
users.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [3]:
users.shape

(943, 4)

In [5]:
users.zip_code.duplicated().sum()

np.int64(148)

In [6]:
users.duplicated().sum()

np.int64(7)

In [10]:
users.loc[users.duplicated(keep='first'),:]

         age gender occupation zip_code
user_id
496       21      F    student    55414
572       51      M   educator    20003
621       17      M    student    60402
684       28      M    student    55414
733       44      F      other    60630
805       27      F      other    20009
890       32      M    student    97301

In [11]:
users.loc[users.duplicated(keep='last'),:]

         age gender occupation zip_code
user_id
67        17      M    student    60402
85        51      M   educator    20003
198       21      F    student    55414
350       32      M    student    97301
428       28      M    student    55414
437       27      F      other    20009
460       44      F      other    60630

In [13]:
users.loc[users.duplicated(keep=False),:]

         age gender occupation zip_code
user_id
67        17      M    student    60402
85        51      M   educator    20003
198       21      F    student    55414
350       32      M    student    97301
428       28      M    student    55414
437       27      F      other    20009
460       44      F      other    60630
496       21      F    student    55414
572       51      M   educator    20003
621       17      M    student    60402
684       28      M    student    55414
733       44      F      other    60630
805       27      F      other    20009
890       32      M    student    97301

In [14]:
users.drop_duplicates(keep= "first").shape

(936, 4)

In [15]:
users.drop_duplicates(keep= "last").shape

(936, 4)

In [16]:
users.duplicated(subset=["age", "zip_code"]).sum()

np.int64(16)

In [18]:
users.drop_duplicates(subset=["age", "zip_code"]).shape

(927, 4)