### Axis parameter

In [8]:
import pandas as pd

In [9]:
drinks = pd.read_csv("http://bit.ly/drinksbycountry")

In [10]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

**Axis 1 = columns**

In [11]:
drinks.drop('continent', axis=1).head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9

**Axis 0 - rows**

In [12]:
drinks.drop(2, axis=0).head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America

In [15]:
drinks.mean(axis=0, numeric_only=True)

beer_servings                   106.160622
spirit_servings                  80.994819
wine_servings                    49.450777
total_litres_of_pure_alcohol      4.717098
dtype: float64

In [16]:
drinks.mean(axis=1, numeric_only=True)

0        0.000
1       69.975
2        9.925
3      176.850
4       81.225
        ...
188    110.925
189     29.000
190      1.525
191     14.375
192     22.675
Length: 193, dtype: float64

In [17]:
drinks.mean(axis=1, numeric_only=True).shape

(193,)

In [18]:
drinks.mean(axis=0, numeric_only=True).shape

(4,)

#### Another way to do

**axis = index**

In [19]:
drinks.mean(axis='index', numeric_only=True)

beer_servings                   106.160622
spirit_servings                  80.994819
wine_servings                    49.450777
total_litres_of_pure_alcohol      4.717098
dtype: float64

**axis ="columns"**

In [20]:
drinks.mean(axis='columns', numeric_only=True)

0        0.000
1       69.975
2        9.925
3      176.850
4       81.225
        ...
188    110.925
189     29.000
190      1.525
191     14.375
192     22.675
Length: 193, dtype: float64