### Index

In [1]:
import pandas as pd

In [2]:
drinks = pd.read_csv("http://bit.ly/drinksbycountry")

In [3]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [4]:
drinks.index

RangeIndex(start=0, stop=193, step=1)

In [5]:
drinks.columns

Index(['country', 'beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='str')

In [6]:
drinks.shape

(193, 6)

In [13]:
pd.read_csv("http://bit.ly/movieusers", sep="|", header=None).head()

   0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [18]:
drinks[drinks.continent == "South America"]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
6,Argentina,193,25,221,8.3,South America
20,Bolivia,167,41,8,3.8,South America
23,Brazil,245,145,16,7.2,South America
35,Chile,130,124,172,7.6,South America
37,Colombia,159,76,3,4.2,South America
52,Ecuador,162,74,3,4.2,South America
72,Guyana,93,302,1,7.1,South America
132,Paraguay,213,117,74,7.3,South America
133,Peru,163,160,21,6.1,South America
163,Suriname,128,178,7,5.6,South America
185,Uruguay,115,35,220,6.6,South America
188,Venezuela,333,100,3,7.7,South America

In [21]:
drinks.set_index("country",inplace=True)

In [22]:
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [23]:
drinks.index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua & Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
       ...
       'Tanzania', 'USA', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='str', name='country', length=193)

In [24]:
drinks.columns

Index(['beer_servings', 'spirit_servings', 'wine_servings',
       'total_litres_of_pure_alcohol', 'continent'],
      dtype='str')

In [25]:
drinks.shape

(193, 5)

In [27]:
drinks.loc["Brazil", "beer_servings"]

np.int64(245)

In [28]:
drinks.index.name=None
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [31]:
drinks.index.name ="country"
drinks.reset_index(inplace=True)
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [32]:
drinks.describe()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
count,193.000000,193.000000,193.000000,193.000000
mean,106.160622,80.994819,49.450777,4.717098
std,101.143103,88.284312,79.697598,3.773298
min,0.000000,0.000000,0.000000,0.000000
25%,20.000000,4.000000,1.000000,1.300000
50%,76.000000,56.000000,8.000000,4.200000
75%,188.000000,128.000000,59.000000,7.200000
max,376.000000,438.000000,370.000000,14.400000

In [33]:
drinks.describe().index

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='str')

In [37]:
drinks.describe().loc["25%","beer_servings"]

np.float64(20.0)

**Series index**

In [38]:
drinks.head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa

In [39]:
drinks.continent

0               Asia
1             Europe
2             Africa
3             Europe
4             Africa
           ...
188    South America
189             Asia
190             Asia
191           Africa
192           Africa
Name: continent, Length: 193, dtype: str

In [40]:
drinks.set_index("country", inplace=True)

In [42]:
drinks.head()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa

In [44]:
drinks.continent.head()

country
Afghanistan      Asia
Albania        Europe
Algeria        Africa
Andorra        Europe
Angola         Africa
Name: continent, dtype: str

In [51]:
drinks.continent.value_counts()

continent
Africa           53
Europe           45
Asia             44
North America    23
Oceania          16
South America    12
Name: count, dtype: int64

In [52]:
drinks.continent.value_counts().values

array([53, 45, 44, 23, 16, 12])

In [53]:
drinks.continent.value_counts()["Africa"]

np.int64(53)

In [54]:
drinks.continent.value_counts().sort_values()

continent
South America    12
Oceania          16
North America    23
Asia             44
Europe           45
Africa           53
Name: count, dtype: int64

In [55]:
drinks.continent.value_counts().sort_index()

continent
Africa           53
Asia             44
Europe           45
North America    23
Oceania          16
South America    12
Name: count, dtype: int64

**aligements**

In [57]:
people = pd.Series([300000,85000],
                   index=["Albania","Andorra"],
                   name="population")
people

Albania    300000
Andorra     85000
Name: population, dtype: int64

In [59]:
drinks.beer_servings * people

country
Afghanistan           NaN
Albania        26700000.0
Algeria               NaN
Andorra        20825000.0
Angola                NaN
                  ...
Venezuela             NaN
Vietnam               NaN
Yemen                 NaN
Zambia                NaN
Zimbabwe              NaN
Length: 193, dtype: float64

In [60]:
pd.concat([drinks, people], axis=1)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent,population
Afghanistan,0,0,0,0.0,Asia,NaN
Albania,89,132,54,4.9,Europe,300000.0
Algeria,25,0,14,0.7,Africa,NaN
Andorra,245,138,312,12.4,Europe,85000.0
Angola,217,57,45,5.9,Africa,NaN
...,...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America,NaN
Vietnam,111,2,1,2.0,Asia,NaN
Yemen,6,0,0,0.1,Asia,NaN
Zambia,32,19,4,2.5,Africa,NaN
Zimbabwe,64,18,4,4.7,Africa,NaN