### How do i Select a Pandas Series from a dataframe?

In [1]:
import pandas as pd

In [3]:
ufo = pd.read_table("http://bit.ly/uforeports", sep =",")
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [4]:
ufo = pd.read_csv("http://bit.ly/uforeports")
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [5]:
type(ufo)

pandas.DataFrame

**Ways to Select Series**

1. Using bracket notation

In [6]:
ufo["City"]

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
                 ...
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: str

In [7]:
type(ufo["City"])

pandas.Series

2. Using dot notation

In [8]:
ufo.City

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
                 ...
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: str

In [11]:
ufo.Colors Reported   # here dot notation will not work

SyntaxError: invalid syntax (1234217996.py, line 1)

In [10]:
ufo["Colors Reported"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
18236    NaN
18237    NaN
18238    NaN
18239    RED
18240    NaN
Name: Colors Reported, Length: 18241, dtype: str

In [12]:
ufo.shape

(18241, 5)

**Bonus tip**

Create new Series in DataFrame

In [13]:
'ab' + "cd"

'abcd'

In [19]:
ufo["Location"] = ufo.City + "," + ufo.State   # here dot noationm will not work

In [20]:
ufo.head()

,City,Colors Reported,Shape Reported,State,Time,Location
0,Ithaca,NaN,TRIANGLE,NY,6/1/1930 22:00,"Ithaca,NY"
1,Willingboro,NaN,OTHER,NJ,6/30/1930 20:00,"Willingboro,NJ"
2,Holyoke,NaN,OVAL,CO,2/15/1931 14:00,"Holyoke,CO"
3,Abilene,NaN,DISK,KS,6/1/1931 13:00,"Abilene,KS"
4,New York Worlds Fair,NaN,LIGHT,NY,4/18/1933 19:00,"New York Worlds Fair,NY"